services:
  clickhouse:
    container_name: "clickhouse-server"
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      # - ./config/users.d/users.xml:/etc/clickhouse-server/users.d//users.xml
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: user123
volumes:
  clickhouse_data: