apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-example
  namespace: default # Same as SecretStore
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault-backend
      kind: SecretStore
  selector: # Select a secret "my-secret" from a cluster
    secret:
      name: my-secret
  data:
    - match:
        secretKey: secretKey # Key matching in "my-secret" secret of a cluster
        remoteRef:
          remoteKey: vault-demo/do-not-delete # Create remote secret under this name