apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://172.18.106.160:30200" # server address
      path: "kv-v2" # secret engine of our secret
      version: "v2"
      auth: # points to a secret that contains a vault token
        tokenSecretRef:
          name: "vault-token"
          key: token