apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  env: beta

labels:
  - pairs:
      backend: nginx

commonAnnotations:
  istio.sidecar.inject: 'false'

nameSuffix: "-nginx"
namePrefix: "beta-"
namespace: "beta"

patches:
  - path: deployment-beta.yaml
  - path: service-beta.yaml