apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-repo
  namespace: ns-argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: "{service-account.yaml,secret.yaml}"
      recurse: true
    path: deployments
    repoURL: https://github.com/HarshPanchal18/argocd-application.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true