apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-scratch
  namespace: argocd
spec:
  destination: # Where should my application deployed
    namespace: default
    server: https://kubernetes.default.svc # Default cluster
  project: experiments
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    helm:
      releaseName: sealed-secrets
    targetRevision: 1.16.1
  syncPolicy:
    automated:       # Apply changes automatically
      prune: true    # Delete resources removed from the git
      selfHeal: true # Revert manual changes in the cluster
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - RespectIgnoreDifferences=false
      - Validate=false
