apiVersion: networking.istio.io/v1beta1
kind: VirtualService

metadata:
  name: app

spec:
  hosts:
  - "*"

  gateways:
  - app-gateway

  http:
  - match:
    - uri:
        prefix: /home

    route:
    - destination:
        host: app
        subset: v1
        weight: 80
    - destination:
        host: app
        subset: v2
        weight: 20
